### ISSUE TITLE
T02: Definir y Bosquejar Arquitectura Lógica

### ISSUE THREAD

**Issue by MrRojano97** [lgsilvestre/SoftProyectAdmin_G2#2]
Esta tarea está dedicada a definir y bosquejar la arquitectura lógica a utilizar en el Sistema. Cabe resaltar que esta puede tener modificaciones a futuro y no es definitiva.

**Comment by MrRojano97** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T02: Definir y Bosquejar Arquitectura Lógica (4)](https://trello.com/c/cejJiGhS/16-t02-definir-y-bosquejar-arquitectura-l%C3%B3gica-4)

**Comment by Thitsugaya1** [comment]
Imagen en la carpeta de arquitectura
