### ISSUE TITLE
T21-2 | T20-2 Estabilidad y Prioridad

### ISSUE THREAD

**Issue by MrRojano97** [lgsilvestre/SoftProyectAdmin_G2#27]
Se añaden las opciones de Estabilidad y Prioridad a los Modal

**Comment by MrRojano97** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T20: Habilitar Requisitos de Usuario (8)](https://trello.com/c/4CDuVoDx/43-t20-habilitar-requisitos-de-usuario-8)

**Comment by MrRojano97** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T21: Habilitar Requisitos de Software (8)](https://trello.com/c/NXVHErv2/44-t21-habilitar-requisitos-de-software-8)

**Comment by Thitsugaya1** [comment]
EXTRA: Eliminacion del boton cancelar de los modales de los requisitos de usuario y sistema
