### ISSUE TITLE
T03: Definir y Bosquejar Arquitectura Física

### ISSUE THREAD

**Issue by MrRojano97** [lgsilvestre/SoftProyectAdmin_G2#3]
En esta tarea se definirá y se hará un bosquejo de cómo será la Arquitectura Física del Sistema, teniendo en cuenta el ambiente en dónde funcionará el Software.

**Comment by MrRojano97** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T03: Definir y Bosquejar Arquitectura Física (2)](https://trello.com/c/H3tBdec3/15-t03-definir-y-bosquejar-arquitectura-f%C3%ADsica-2)

**Comment by Thitsugaya1** [comment]
Imagen en la carpeta de arquitectura
