### ISSUE TITLE
T04: Bosquejar Modelos de Clases

### ISSUE THREAD

**Issue by MrRojano97** [lgsilvestre/SoftProyectAdmin_G2#4]
Se realizará un bosquejo de los modelos de clases que se utilizarán para el proyecto, este puede estar sujeto a cambios futuros según la necesidad del sistema.

**Comment by MrRojano97** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T04: Bosquejar Modelos de Clases (12)](https://trello.com/c/8AILsg8O/17-t04-bosquejar-modelos-de-clases-12)

**Comment by Thitsugaya1** [comment]
Completado con @Crist0ba1
